Attribute VB_Name = "modGanttConfig"
Option Explicit

Public Const GANTT_HEADER_ROW_MONTH As Long = 1
Public Const GANTT_HEADER_ROW_WEEK As Long = 2
Public Const GANTT_HEADER_ROW_DAY As Long = 3
Public Const GANTT_HEADER_ROW_DATE As Long = 4

Public Const HEADER_ROW As Long = 4
Public Const DATA_START_ROW As Long = 5

Public Const COL_NO As String = "B"
Public Const COL_LEVEL As String = "C"
Public Const COL_MODULE As String = "D"
Public Const COL_TASK As String = "E"
Public Const COL_OWNER As String = "F"
Public Const COL_NOTE As String = "G"
Public Const COL_PLAN_START As String = "H"
Public Const COL_PLAN_END As String = "I"
Public Const COL_ACTUAL_START As String = "J"
Public Const COL_ACTUAL_END As String = "K"
Public Const COL_PROGRESS As String = "L"
Public Const COL_NORMAL_PROGRESS As String = "M"
Public Const COL_MANUAL_PROGRESS As String = "N"
Public Const COL_MANUAL_STATUS As String = "O"
Public Const COL_WEEKLY_REPORT As String = "P"
Public Const COL_DEV_PROGRESS As String = "Q"
Public Const COL_PLAN_DAYS As String = "R"
Public Const COL_ACTUAL_DAYS As String = "S"
Public Const COL_STATUS As String = "T"
Public Const COL_GANTT_START As String = "U"

Public Const CONFIG_SHEET_NAME As String = "config"
Public Const REPORT_HISTORY_SHEET_NAME As String = "ReportHistory"
Public Const LEGACY_CONFIG_SHEET_NAME As String = "휴일설정"
Public Const HOLIDAY_HEADER_ROW As Long = 1
Public Const HOLIDAY_DATA_START_ROW As Long = 2

Public Const HOLIDAY_COL_DATE As String = "A"
Public Const HOLIDAY_COL_TYPE As String = "B"
Public Const HOLIDAY_COL_DESC As String = "C"

Public Const HOLIDAY_TYPE_HOLIDAY As String = "휴일"
Public Const HOLIDAY_TYPE_WORKDAY As String = "근무일"

Public Const HIDE_SETTING_TITLE_CELL As String = "F1"
Public Const HIDE_SETTING_LEVEL_LABEL_CELL As String = "F2"
Public Const HIDE_SETTING_LEVEL_VALUE_CELL As String = "G2"
Public Const DISPLAY_SETTING_TITLE_CELL As String = "I1"
Public Const DISPLAY_SETTING_START_LABEL_CELL As String = "I2"
Public Const DISPLAY_SETTING_START_VALUE_CELL As String = "J2"
Public Const DISPLAY_SETTING_END_LABEL_CELL As String = "I3"
Public Const DISPLAY_SETTING_END_VALUE_CELL As String = "J3"
Public Const DISPLAY_SETTING_GANTT_ONLY_LABEL_CELL As String = "I4"
Public Const DISPLAY_SETTING_GANTT_ONLY_VALUE_CELL As String = "J4"
Public Const DISPLAY_SETTING_REPORT_ONLY_LABEL_CELL As String = "I5"
Public Const DISPLAY_SETTING_REPORT_ONLY_VALUE_CELL As String = "J5"
Public Const INPUT_SETTING_TITLE_CELL As String = "I7"
Public Const TASK_MAX_LENGTH_LABEL_RANGE As String = "I8:I10"
Public Const TASK_MAX_LENGTH_VALUE_RANGE As String = "J8:J10"
Public Const TASK_MAX_LENGTH_LEVEL1_LABEL_CELL As String = "I8"
Public Const TASK_MAX_LENGTH_LEVEL1_VALUE_CELL As String = "J8"
Public Const TASK_MAX_LENGTH_LEVEL2_LABEL_CELL As String = "I9"
Public Const TASK_MAX_LENGTH_LEVEL2_VALUE_CELL As String = "J9"
Public Const TASK_MAX_LENGTH_LEVEL3_LABEL_CELL As String = "I10"
Public Const TASK_MAX_LENGTH_LEVEL3_VALUE_CELL As String = "J10"
Public Const TASK_MAX_LENGTH_LABEL_CELL As String = TASK_MAX_LENGTH_LEVEL1_LABEL_CELL
Public Const TASK_MAX_LENGTH_VALUE_CELL As String = TASK_MAX_LENGTH_LEVEL1_VALUE_CELL
Public Const DEFAULT_TASK_MAX_LENGTH As Long = 30
Public Const MIN_TASK_MAX_LENGTH As Long = 1
Public Const MAX_TASK_MAX_LENGTH As Long = 1000
Public Const DEV_REPORT_SETTING_TITLE_CELL As String = "L1"
Public Const DEV_REPORT_LAYOUT_LABEL_CELL As String = "L2"
Public Const DEV_REPORT_LAYOUT_VALUE_CELL As String = "M2"
Public Const DEV_REPORT_LAYOUT_CURRENT As String = "모듈별 통합"
Public Const DEV_REPORT_LAYOUT_BY_STATUS As String = "상태별 구분"
Public Const DEV_REPORT_BULLET_TITLE_CELL As String = "L4"
Public Const DEV_REPORT_BULLET_LEVEL1_LABEL_CELL As String = "L5"
Public Const DEV_REPORT_BULLET_LEVEL1_VALUE_CELL As String = "M5"
Public Const DEV_REPORT_BULLET_LEVEL2_LABEL_CELL As String = "L6"
Public Const DEV_REPORT_BULLET_LEVEL2_VALUE_CELL As String = "M6"
Public Const DEV_REPORT_BULLET_LEVEL3_LABEL_CELL As String = "L7"
Public Const DEV_REPORT_BULLET_LEVEL3_VALUE_CELL As String = "M7"
Public Const WEEKLY_REPORT_SETTING_TITLE_CELL As String = "O1"
Public Const WEEKLY_REPORT_OWNER_LABEL_CELL As String = "O2"
Public Const WEEKLY_REPORT_OWNER_VALUE_CELL As String = "P2"
Public Const WEEKLY_REPORT_PAGE_MODE_LABEL_CELL As String = "O3"
Public Const WEEKLY_REPORT_PAGE_MODE_VALUE_CELL As String = "P3"
Public Const WEEKLY_REPORT_CUSTOM_PAGE_HEADER_CELL As String = "O5"
Public Const WEEKLY_REPORT_CUSTOM_MODULE_HEADER_CELL As String = "P5"
Public Const WEEKLY_REPORT_CUSTOM_PAGE_COLUMN As String = "O"
Public Const WEEKLY_REPORT_CUSTOM_MODULE_COLUMN As String = "P"
Public Const WEEKLY_REPORT_CUSTOM_START_ROW As Long = 6
Public Const WEEKLY_REPORT_CUSTOM_END_ROW As Long = 200
Public Const WEEKLY_REPORT_MODULE_LIST_COLUMN As String = "AA"
Public Const WEEKLY_REPORT_MODULE_LIST_START_ROW As Long = 2
Public Const WEEKLY_REPORT_PAGE_MODE_ALL As String = "전체 통합"
Public Const WEEKLY_REPORT_PAGE_MODE_MODULE As String = "모듈별 페이지"
Public Const WEEKLY_REPORT_PAGE_MODE_CUSTOM As String = "커스텀 페이지"
Public Const HIDE_EXCLUDE_NO_HEADER_CELL As String = "F5"
Public Const HIDE_EXCLUDE_DATE_HEADER_CELL As String = "G5"
Public Const HIDE_EXCLUDE_NO_START_CELL As String = "F6"
Public Const HIDE_EXCLUDE_DATE_START_CELL As String = "G6"

Public Const STATUS_NORMAL As String = "정상"
Public Const STATUS_CAUTION As String = "주의"
Public Const STATUS_DELAY As String = "지연"
Public Const STATUS_DONE As String = "완료"
Public Const STATUS_HOLD As String = "보류"
Public Const STATUS_WEEKLY_REPORT As String = "주간보고"
Public Const STATUS_DEV_PROGRESS As String = "개발진행"
Public Const STATUS_REPORT_DONE As String = "보고완료"
Public Const STATUS_ERROR As String = "오류"
Public Const REPORT_FILTER_ALL As String = "전체"
Public Const REPORT_FILTER_EMPTY As String = "빈값"
Public Const REPORT_STATUS_PLANNED As String = "Planned"
Public Const REPORT_STATUS_IN_PROGRESS As String = "In Progress"
Public Const REPORT_STATUS_COMPLETED As String = "Completed"
Public Const STATUS_DONE_WITH_HOLD_SUFFIX As String = "(보류 포함)"
